#!/bin/bash
set -e -u -o pipefail

source /app/ovpn/get-ovpn-files.sh
source /app/ovpn/servers_recommendations.sh

. /app/date.sh --source-only

# Create a tun device see: https://www.kernel.org/doc/Documentation/networking/tuntap.txt
if [ ! -c /dev/net/tun ]; then
    echo "$(adddate) INFO: Creating tun interface /dev/net/tun"
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200
    chmod 600 /dev/net/tun
fi

echo ########################################################
echo "$(adddate) INFO: Connection to server: $SERVERNAME"
echo "$(adddate) INFO: Current load: $LOAD"
echo "$(adddate) INFO: Info updated at: $UPDATED_AT"
echo "$(adddate) INFO: Server IP: $IP"
echo "$(adddate) INFO: Protocol: $PROTOCOL"
echo ########################################################

cd /app/ovpn/config/ovpn_${PROTOCOL,,}

if [ -n "$SERVER" ]; then
  set -- "$@" '--config' "${SERVER}.${PROTOCOL,,}.ovpn"
else
  echo "$(adddate) ERROR: No OpenVPN config found in `pwd`/${SERVER}.${PROTOCOL,,}.ovpn. Exiting."
  exit 1
fi

AUTH_CONF_FILE=auth.conf
if [ -n "$USERNAME_FILE" ]; then
  cat "$USERNAME_FILE" > $AUTH_CONF_FILE
elif [ -n "$USERNAME" ]; then
  echo "$USERNAME" > $AUTH_CONF_FILE
else
  echo "$(adddate) ERROR: No username credential available, please fill in the ENVIRONMENT variable USERNAME or USERNAME_FILE (to use Docker Secret). Exiting"
  exit 1
fi
if [ -n "$PASSWORD_FILE" ]; then
  # Add return char before password
  echo "" >> $AUTH_CONF_FILE
  cat "$PASSWORD_FILE" >> $AUTH_CONF_FILE
elif [ -n "$PASSWORD" ]; then
  echo "$PASSWORD" >> $AUTH_CONF_FILE
else
  echo "$(adddate) ERROR: No password credential available, please fill in the ENVIRONMENT variable PASSWORD or PASSWORD_FILE (to use Docker Secret). Exiting"
  exit 1
fi
chmod 600 $AUTH_CONF_FILE
set -- "$@" '--auth-user-pass' "$AUTH_CONF_FILE"

openvpn "$@"
